name: ba3l
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.10.11
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - python=3.8.16
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
    - absl-py==1.4.0
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - appdirs==1.4.4
    - async-timeout==4.0.2
    - attrs==22.2.0
    - audioread==3.0.0
    - av==10.0.0
    - cachetools==5.3.0
    - cffi==1.15.1
    - charset-normalizer==3.0.1
    - colorama==0.4.6
    - decorator==5.1.1
    - docopt==0.6.2
    - frozenlist==1.3.3
    - fsspec==2023.3.0
    - future==0.18.3
    - gitdb==4.0.10
    - gitpython==3.1.31
    - google-auth==2.17.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.53.0
    - h5py==3.8.0
    - idna==3.4
    - imageio==2.27.0
    - importlib-metadata==6.1.0
    - joblib==1.2.0
    - jsonpickle==3.0.1
    - kk-sacred==0.8.4
    - lazy-loader==0.2
    - librosa==0.10.0.post2
    - llvmlite==0.39.1
    - markdown==3.4.3
    - markupsafe==2.1.2
    - msgpack==1.0.5
    - multidict==6.0.4
    - munch==2.5.0
    - numba==0.56.4
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauthlib==3.2.2
    - packaging==23.0
    - pandas==1.5.3
    - pillow==9.4.0
    - pooch==1.6.0
    - protobuf==4.22.1
    - py-cpuinfo==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - python-dateutil==2.8.2
    - pytorch-lightning==1.3.0.dev0
    - pytz==2023.3
    - pyyaml==6.0
    - requests==2.28.2
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - six==1.16.0
    - smmap==5.0.0
    - soundfile==0.12.1
    - soxr==0.3.4
    - tensorboard==2.12.0
    - tensorboard-data-server==0.7.0
    - tensorboard-plugin-wit==1.8.1
    - test-tube==0.7.5
    - threadpoolctl==3.1.0
    - timm==0.4.12
    - torch==1.13.1
    - torchaudio==0.13.1
    - torchmetrics==0.2.0
    - torchvision==0.14.1
    - tqdm==4.65.0
    - typing-extensions==4.4.0
    - urllib3==1.26.14
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - yarl==1.8.2
    - zipp==3.15.0
